# Generated by Django 5.2.7 on 2025-10-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
