# Generated by Django 5.2.7 on 2025-10-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0004_game_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
    ]
