# Generated by Django 5.2.7 on 2025-10-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0005_remove_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
